apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: { { .Values.appName.auth } }
  name: { { .Values.appName.auth } }
  namespace: { { .Values.namespace } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: { { .Values.appName.auth } }
  template:
    metadata:
      labels:
        app: { { .Values.appName.auth } }
    spec:
      containers:
        - image: "{ { .Values.image.name } }:{{ .Values.image.tag }}"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: { { .Values.appName.auth } }
  name: { { .Values.appName.auth } }
  namespace: { { .Values.namespace } }
spec:
  ports:
    - name: { { .Values.appName.auth } }
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: { { .Values.appName.auth } }
