apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
  namespace: { { .Values.namespace } }
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - image: "{ { .Values.image.name } }:{{ .Values.image.tag }}"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth
  namespace: { { .Values.namespace } }
spec:
  ports:
    - name: auth
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: auth
